name: "Dependaction - Create Pull Requests"
description: "Creates a pull request"
inputs:
  matrix: # id of input
    description: "Input from group-by action"
    required: true
  install-command:
    description: "bash command to install"
    required: false
    default: "npm i --legacy-peer-deps"
  labels:
    required: false
    default: "dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
        registry-url: "https://registry.npmjs.org"
    - run: node ${{ github.action_path }}/dist/index.js '${{ toJSON(inputs.matrix) }}'
      shell: bash
    - run: ${{ inputs.install-command }} || true
      shell: bash
    - run: git status
      shell: bash
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Bump ${{ fromJson(inputs.matrix).displayName }} from ${{ fromJson(inputs.matrix).groupCurrentVersion }} to ${{ fromJson(inputs.matrix).groupLatestVersion }}
        title: Bump ${{ fromJson(inputs.matrix).displayName }} from ${{ fromJson(inputs.matrix).groupCurrentVersion }} to ${{ fromJson(inputs.matrix).groupLatestVersion }}
        body: ${{ fromJson(inputs.matrix).prBody }}
        assignees: rgdelato
        reviewers: rgdelato
        branch: bump-${{ fromJson(inputs.matrix).slug }}
        branch-suffix: short-commit-hash
        labels: ${{ fromJson(inputs.matrix).semverLabel }},dependaction,${{ inputs.labels }}
        delete-branch: true
