name: "Dependaction - Create Pull Requests"
description: "Creates a pull request"
inputs:
  token:
    required: false
    default: ${{ github.token }}
  matrix: # id of input
    required: true
  install-command:
    required: false
    default: "npm i --legacy-peer-deps"
  sleep:
    required: false
    default: "0"
  assignees:
    required: false
    default: ""
  assignees-major:
    required: false
    default: ""
  assignees-minor:
    required: false
    default: ""
  assignees-patch:
    required: false
    default: ""
  reviewers:
    required: false
    default: ""
  reviewers-major:
    required: false
    default: ""
  reviewers-minor:
    required: false
    default: ""
  reviewers-patch:
    required: false
    default: ""
  team-reviewers:
    required: false
    default: ""
  team-reviewers-major:
    required: false
    default: ""
  team-reviewers-minor:
    required: false
    default: ""
  team-reviewers-patch:
    required: false
    default: ""
  labels:
    required: false
    default: ""
outputs:
  data: # id of output
    description: "Data for the pull request"
    value: ${{ steps.script.outputs.data }}
  assignees: # id of output
    description: "Assignees depending on major/minor/patch version"
    value: ${{ steps.assignees.outputs.assignees }}
  reviewers: # id of output
    description: "Reviewers depending on major/minor/patch version"
    value: ${{ steps.reviewers.outputs.reviewers }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
        registry-url: "https://registry.npmjs.org"
    - id: script
      run: |
        echo $(node ${{ github.action_path }}/dist/index.js '${{ toJSON(inputs.matrix) }}')
      shell: bash
    - id: install
      run: |
        ${{ inputs.install-command }} || true
        git status
      shell: bash
    - id: assignees
      run: |
        if [ "${{ fromJson(inputs.matrix).semverLabel }}" == "major" ]; then echo "::set-output name=assignees::${{ inputs.assignees-major }}";
        elif [ "${{ fromJson(inputs.matrix).semverLabel }}" == "minor" ]; then echo "::set-output name=assignees::${{ inputs.assignees-minor }}";
        elif [ "${{ fromJson(inputs.matrix).semverLabel }}" == "patch" ]; then echo "::set-output name=assignees::${{ inputs.assignees-patch }}"; fi
      shell: bash
    - id: reviewers
      run: |
        if [ "${{ fromJson(inputs.matrix).semverLabel }}" == "major" ]; then echo "::set-output name=reviewers::${{ inputs.reviewers-major }}";
        elif [ "${{ fromJson(inputs.matrix).semverLabel }}" == "minor" ]; then echo "::set-output name=reviewers::${{ inputs.reviewers-minor }}";
        elif [ "${{ fromJson(inputs.matrix).semverLabel }}" == "patch" ]; then echo "::set-output name=reviewers::${{ inputs.reviewers-patch }}"; fi
      shell: bash
    - id: team-reviewers
      run: |
        if [ "${{ fromJson(inputs.matrix).semverLabel }}" == "major" ]; then echo "::set-output name=team-reviewers::${{ inputs.team-reviewers-major }}";
        elif [ "${{ fromJson(inputs.matrix).semverLabel }}" == "minor" ]; then echo "::set-output name=team-reviewers::${{ inputs.team-reviewers-minor }}";
        elif [ "${{ fromJson(inputs.matrix).semverLabel }}" == "patch" ]; then echo "::set-output name=team-reviewers::${{ inputs.team-reviewers-patch }}"; fi
      shell: bash
    - id: create-pull-request
      name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ inputs.token }}
        commit-message: Bump ${{ fromJson(inputs.matrix).displayName }} from ${{ fromJson(inputs.matrix).groupCurrentVersion }} to ${{ fromJson(inputs.matrix).groupLatestVersion }}
        title: Bump ${{ fromJson(inputs.matrix).displayName }} from ${{ fromJson(inputs.matrix).groupCurrentVersion }} to ${{ fromJson(inputs.matrix).groupLatestVersion }}
        body: ${{ fromJson(inputs.matrix).prBody }}
        assignees: ${{ inputs.assignees }},${{ steps.assignees.outputs.assignees }}
        reviewers: ${{ inputs.reviewers }},${{ steps.reviewers.outputs.reviewers }}
        team-reviewers: ${{ inputs.team-reviewers }},${{ steps.team-reviewers.outputs.team-reviewers }}
        branch: dependaction-${{ fromJson(inputs.matrix).hash }}
        labels: |
          dependaction
          ${{ fromJson(inputs.matrix).semverLabel }}
          ${{ inputs.labels }}
        delete-branch: true
    - id: sleep
      run: sleep ${{ inputs.sleep }}
      shell: bash
    - id: approve-pull-request
      name: Auto-approve pull request
      if: steps.create-pull-request.outputs.pull-request-operation == 'created'
      uses: juliangruber/approve-pull-request-action@v1
      with:
        github-token: ${{ github.token }}
        number: ${{ steps.create-pull-request.outputs.pull-request-number }}
